from __future__ import annotations

import uuid
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy import func, or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.dependencies import get_current_admin
from app.database.session import get_db
from app.models.lead import Lead, LeadActivity, LeadSource, LeadStatus
from app.models.tenant import Tenant
from app.models.user import User
from app.services.free_lead_generation import (
    LeadSourceUnavailableError,
    LocationNotFoundError,
    discover_public_business_leads,
)


router = APIRouter(prefix="/admin/lead-generation", tags=["Admin Lead Generation"])


class LeadGenerationSearchRequest(BaseModel):
    industry: str = Field(min_length=2, max_length=80)
    location: str = Field(min_length=2, max_length=160)
    radius_km: int = Field(default=5, ge=1, le=25)
    limit: int = Field(default=25, ge=5, le=50)


class LeadCandidate(BaseModel):
    id: str
    name: str
    category: str
    address: Optional[str] = None
    phone: Optional[str] = None
    email: Optional[str] = None
    website: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    score: int = Field(ge=0, le=100)
    source: str
    source_url: str


class LeadGenerationSearchResponse(BaseModel):
    industry: str
    location: str
    resolved_location: str
    radius_km: int
    provider: str
    attribution_url: str
    result_count: int
    candidates: List[LeadCandidate]


class LeadGenerationImportRequest(BaseModel):
    tenant_id: str
    candidates: List[LeadCandidate] = Field(min_length=1, max_length=50)


class LeadGenerationImportResponse(BaseModel):
    imported_count: int
    skipped_count: int
    imported_lead_ids: List[str]
    skipped_candidate_ids: List[str]
    message: str


@router.post("/search", response_model=LeadGenerationSearchResponse)
async def search_public_business_leads(
    data: LeadGenerationSearchRequest,
    current_user: User = Depends(get_current_admin),
):
    del current_user
    try:
        result = await discover_public_business_leads(
            industry=data.industry.strip(),
            location=data.location.strip(),
            radius_km=data.radius_km,
            limit=data.limit,
        )
    except LocationNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc
    except LeadSourceUnavailableError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        ) from exc

    candidates = [LeadCandidate(**candidate) for candidate in result["candidates"]]
    return LeadGenerationSearchResponse(
        industry=result["industry"],
        location=result["location"],
        resolved_location=result["resolved_location"],
        radius_km=result["radius_km"],
        provider=result["provider"],
        attribution_url=result["attribution_url"],
        result_count=len(candidates),
        candidates=candidates,
    )


def _candidate_notes(candidate: LeadCandidate) -> str:
    details = [
        "Generated by MME-AI Free Lead Generation Agent",
        f"Category: {candidate.category}",
        f"Source: {candidate.source}",
        f"Source URL: {candidate.source_url}",
    ]
    if candidate.website:
        details.append(f"Website: {candidate.website}")
    if candidate.address:
        details.append(f"Address: {candidate.address}")
    return "\n".join(details)


@router.post(
    "/import",
    response_model=LeadGenerationImportResponse,
    status_code=status.HTTP_201_CREATED,
)
async def import_generated_leads(
    data: LeadGenerationImportRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_admin),
):
    tenant_result = await db.execute(select(Tenant).where(Tenant.id == data.tenant_id))
    tenant = tenant_result.scalar_one_or_none()
    if not tenant:
        raise HTTPException(status_code=404, detail="Client company not found")
    if not tenant.is_active:
        raise HTTPException(status_code=400, detail="Client company is inactive")

    imported_ids: List[str] = []
    skipped_ids: List[str] = []

    for candidate in data.candidates:
        duplicate_checks = [func.lower(Lead.name) == candidate.name.lower()]
        if candidate.email:
            duplicate_checks.append(func.lower(Lead.email) == candidate.email.lower())
        if candidate.phone:
            duplicate_checks.append(Lead.phone == candidate.phone)

        duplicate_result = await db.execute(
            select(Lead.id).where(
                Lead.tenant_id == tenant.id,
                or_(*duplicate_checks),
            )
        )
        if duplicate_result.scalars().first():
            skipped_ids.append(candidate.id)
            continue

        lead = Lead(
            id=str(uuid.uuid4()),
            tenant_id=tenant.id,
            name=candidate.name,
            email=candidate.email,
            phone=candidate.phone,
            source=LeadSource.other.value,
            status=LeadStatus.new.value,
            score=candidate.score,
            notes=_candidate_notes(candidate),
            is_active=True,
        )
        db.add(lead)
        await db.flush()
        db.add(
            LeadActivity(
                id=str(uuid.uuid4()),
                lead_id=lead.id,
                activity_type="lead_agent_import",
                description=f"Imported from {candidate.source} by the free lead generation agent",
                created_by=current_user.id,
            )
        )
        imported_ids.append(lead.id)

    await db.commit()
    return LeadGenerationImportResponse(
        imported_count=len(imported_ids),
        skipped_count=len(skipped_ids),
        imported_lead_ids=imported_ids,
        skipped_candidate_ids=skipped_ids,
        message=(
            f"Imported {len(imported_ids)} leads into {tenant.name}. "
            f"Skipped {len(skipped_ids)} possible duplicates."
        ),
    )
